name: Docker Publish on Tag

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to Docker Hub (or other container registries)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta_web
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/grafana-proxy # Updated image name
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha # Also tag with commit SHA

    - name: Build and push GrafanaProxy.Web
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile.web
        push: true
        tags: ${{ steps.meta_web.outputs.tags }}
        labels: ${{ steps.meta_web.outputs.labels }}

    - name: Extract metadata (tags, labels) for Docker - Management API
      id: meta_management
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/grafana-proxy-api # Updated image name
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha # Also tag with commit SHA

    - name: Build and push GrafanaProxy.Management.Api
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile.management
        push: true
        tags: ${{ steps.meta_management.outputs.tags }}
        labels: ${{ steps.meta_management.outputs.labels }} 